-- Raja Ongkir destination mirror (Komerce API)
-- Generated by scripts/extract-raja-ongkir.ts

CREATE TABLE IF NOT EXISTS raja_provinces (
  id BIGINT PRIMARY KEY,
  name TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS raja_cities (
  id BIGINT PRIMARY KEY,
  province_id BIGINT NOT NULL REFERENCES raja_provinces (id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  zip_code TEXT
);

CREATE TABLE IF NOT EXISTS raja_districts (
  id BIGINT PRIMARY KEY,
  city_id BIGINT NOT NULL REFERENCES raja_cities (id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  zip_code TEXT
);

CREATE TABLE IF NOT EXISTS raja_sub_districts (
  id BIGINT PRIMARY KEY,
  district_id BIGINT NOT NULL REFERENCES raja_districts (id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  zip_code TEXT
);

CREATE INDEX IF NOT EXISTS idx_raja_cities_province ON raja_cities (province_id);
CREATE INDEX IF NOT EXISTS idx_raja_districts_city ON raja_districts (city_id);
CREATE INDEX IF NOT EXISTS idx_raja_sub_districts_district ON raja_sub_districts (district_id);
