-- Raja Ongkir destination mirror (Komerce API)
-- Generated by scripts/extract-raja-ongkir.ts

CREATE TABLE IF NOT EXISTS provinces (
  id BIGINT PRIMARY KEY,
  name TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS cities (
  id BIGINT PRIMARY KEY,
  province_id BIGINT NOT NULL REFERENCES provinces (id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  zip_code TEXT
);

CREATE TABLE IF NOT EXISTS districts (
  id BIGINT PRIMARY KEY,
  city_id BIGINT NOT NULL REFERENCES cities (id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  zip_code TEXT
);

CREATE TABLE IF NOT EXISTS sub_districts (
  id BIGINT PRIMARY KEY,
  district_id BIGINT NOT NULL REFERENCES districts (id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  zip_code TEXT
);

CREATE INDEX IF NOT EXISTS idx_cities_province ON cities (province_id);
CREATE INDEX IF NOT EXISTS idx_districts_city ON districts (city_id);
CREATE INDEX IF NOT EXISTS idx_sub_districts_district ON sub_districts (district_id);
