import type { CrawlResult } from "@/types/index";

export function sqlString(value: string | number | null | undefined): string {
  if (value === null || value === undefined) return "NULL";
  const s = String(value);
  return `'${s.replace(/'/g, "''")}'`;
}

export function batchedInserts(
  table: string,
  cols: string[],
  rows: string[][],
  batchSize: number,
): string {
  if (rows.length === 0) return "";
  const colList = cols.join(", ");
  let out = "";
  for (let i = 0; i < rows.length; i += batchSize) {
    const chunk = rows.slice(i, i + batchSize);
    const values = chunk.map((r) => `(${r.join(", ")})`).join(",\n");
    out += `INSERT INTO ${table} (${colList})\nVALUES\n${values};\n\n`;
  }
  return out;
}

export const SCHEMA_DDL = `-- Raja Ongkir destination mirror (Komerce API)
-- Generated by scripts/extract-raja-ongkir.ts

CREATE TABLE IF NOT EXISTS raja_provinces (
  id BIGINT PRIMARY KEY,
  name TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS raja_cities (
  id BIGINT PRIMARY KEY,
  province_id BIGINT NOT NULL REFERENCES raja_provinces (id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  zip_code TEXT
);

CREATE TABLE IF NOT EXISTS raja_districts (
  id BIGINT PRIMARY KEY,
  city_id BIGINT NOT NULL REFERENCES raja_cities (id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  zip_code TEXT
);

CREATE TABLE IF NOT EXISTS raja_sub_districts (
  id BIGINT PRIMARY KEY,
  district_id BIGINT NOT NULL REFERENCES raja_districts (id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  zip_code TEXT
);

CREATE INDEX IF NOT EXISTS idx_raja_cities_province ON raja_cities (province_id);
CREATE INDEX IF NOT EXISTS idx_raja_districts_city ON raja_districts (city_id);
CREATE INDEX IF NOT EXISTS idx_raja_sub_districts_district ON raja_sub_districts (district_id);
`;

function zipSql(zip: string | null): string {
  return zip == null ? "NULL" : sqlString(zip);
}

export function buildSeedSql(data: CrawlResult, batchSize: number): string {
  const cityEntries = [...data.cities.entries()].sort((a, b) => a[0] - b[0]);
  const districtEntries = [...data.districts.entries()].sort((a, b) => a[0] - b[0]);

  const provinceRows: string[][] = data.provinces.map((p) => [
    String(p.id),
    sqlString(p.name),
  ]);

  const cityRows: string[][] = cityEntries.map(([id, row]) => [
    String(id),
    String(row.province_id),
    sqlString(row.name),
    zipSql(row.zip_code),
  ]);

  const districtRows: string[][] = districtEntries.map(([id, row]) => [
    String(id),
    String(row.city_id),
    sqlString(row.name),
    zipSql(row.zip_code),
  ]);

  const subRows: string[][] = data.subDistricts.map((s) => [
    String(s.id),
    String(s.district_id),
    sqlString(s.name),
    zipSql(s.zip_code),
  ]);

  return (
    `-- Raja Ongkir seed (destructive truncate of raja_* only)\nBEGIN;\n\n` +
    `TRUNCATE raja_sub_districts, raja_districts, raja_cities, raja_provinces RESTART IDENTITY CASCADE;\n\n` +
    batchedInserts("raja_provinces", ["id", "name"], provinceRows, batchSize) +
    batchedInserts(
      "raja_cities",
      ["id", "province_id", "name", "zip_code"],
      cityRows,
      batchSize,
    ) +
    batchedInserts(
      "raja_districts",
      ["id", "city_id", "name", "zip_code"],
      districtRows,
      batchSize,
    ) +
    batchedInserts(
      "raja_sub_districts",
      ["id", "district_id", "name", "zip_code"],
      subRows,
      batchSize,
    ) +
    `COMMIT;\n`
  );
}

export async function writeSqlFiles(
  outDir: string,
  data: CrawlResult,
  batchSize: number,
): Promise<{ schemaPath: string; seedPath: string }> {
  const schemaPath = `${outDir}/schema.sql`;
  const seedPath = `${outDir}/seed.sql`;
  await Bun.write(schemaPath, SCHEMA_DDL);
  await Bun.write(seedPath, buildSeedSql(data, batchSize));
  return { schemaPath, seedPath };
}
