import type { CrawlResult, TableNames } from "@/types/index";

export function sqlString(value: string | number | null | undefined): string {
  if (value === null || value === undefined) return "NULL";
  const s = String(value);
  return `'${s.replace(/'/g, "''")}'`;
}

export function batchedInserts(
  table: string,
  cols: string[],
  rows: string[][],
  batchSize: number,
): string {
  if (rows.length === 0) return "";
  const colList = cols.join(", ");
  let out = "";
  for (let i = 0; i < rows.length; i += batchSize) {
    const chunk = rows.slice(i, i + batchSize);
    const values = chunk.map((r) => `(${r.join(", ")})`).join(",\n");
    out += `INSERT INTO ${table} (${colList})\nVALUES\n${values};\n\n`;
  }
  return out;
}

export function buildSchemaDdl(tables: TableNames): string {
  const { provinces, cities, districts, subDistricts } = tables;
  return `-- Raja Ongkir destination mirror (Komerce API)
-- Generated by extract-raja-ongkir

CREATE TABLE IF NOT EXISTS ${provinces} (
  id BIGINT PRIMARY KEY,
  name TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS ${cities} (
  id BIGINT PRIMARY KEY,
  province_id BIGINT NOT NULL REFERENCES ${provinces} (id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  zip_code TEXT
);

CREATE TABLE IF NOT EXISTS ${districts} (
  id BIGINT PRIMARY KEY,
  city_id BIGINT NOT NULL REFERENCES ${cities} (id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  zip_code TEXT
);

CREATE TABLE IF NOT EXISTS ${subDistricts} (
  id BIGINT PRIMARY KEY,
  district_id BIGINT NOT NULL REFERENCES ${districts} (id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  zip_code TEXT
);

CREATE INDEX IF NOT EXISTS idx_${cities}_province ON ${cities} (province_id);
CREATE INDEX IF NOT EXISTS idx_${districts}_city ON ${districts} (city_id);
CREATE INDEX IF NOT EXISTS idx_${subDistricts}_district ON ${subDistricts} (district_id);
`;
}

function zipSql(zip: string | null): string {
  return zip == null ? "NULL" : sqlString(zip);
}

export function buildSeedSql(
  data: CrawlResult,
  batchSize: number,
  tables: TableNames,
): string {
  const { provinces, cities, districts, subDistricts } = tables;
  const cityEntries = [...data.cities.entries()].sort((a, b) => a[0] - b[0]);
  const districtEntries = [...data.districts.entries()].sort((a, b) => a[0] - b[0]);

  const provinceRows: string[][] = data.provinces.map((p) => [
    String(p.id),
    sqlString(p.name),
  ]);

  const cityRows: string[][] = cityEntries.map(([id, row]) => [
    String(id),
    String(row.province_id),
    sqlString(row.name),
    zipSql(row.zip_code),
  ]);

  const districtRows: string[][] = districtEntries.map(([id, row]) => [
    String(id),
    String(row.city_id),
    sqlString(row.name),
    zipSql(row.zip_code),
  ]);

  const subRows: string[][] = data.subDistricts.map((s) => [
    String(s.id),
    String(s.district_id),
    sqlString(s.name),
    zipSql(s.zip_code),
  ]);

  const tableList = [subDistricts, districts, cities, provinces].join(", ");

  return (
    `-- Raja Ongkir seed (TRUNCATE: ${tableList})\nBEGIN;\n\n` +
    `TRUNCATE ${tableList} RESTART IDENTITY CASCADE;\n\n` +
    batchedInserts(provinces, ["id", "name"], provinceRows, batchSize) +
    batchedInserts(
      cities,
      ["id", "province_id", "name", "zip_code"],
      cityRows,
      batchSize,
    ) +
    batchedInserts(
      districts,
      ["id", "city_id", "name", "zip_code"],
      districtRows,
      batchSize,
    ) +
    batchedInserts(
      subDistricts,
      ["id", "district_id", "name", "zip_code"],
      subRows,
      batchSize,
    ) +
    `COMMIT;\n`
  );
}

export async function writeSqlFiles(
  outDir: string,
  data: CrawlResult,
  batchSize: number,
  tables: TableNames,
): Promise<{ schemaPath: string; seedPath: string }> {
  const schemaPath = `${outDir}/schema.sql`;
  const seedPath = `${outDir}/seed.sql`;
  await Bun.write(schemaPath, buildSchemaDdl(tables));
  await Bun.write(seedPath, buildSeedSql(data, batchSize, tables));
  return { schemaPath, seedPath };
}
